[source]

[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = '/home/deer/suricata/software_package/suricata-7.0.6/rust/vendor'
